### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [CrossEngage/gtm-tracking-sdk-event#1]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1) We are seeing error "Attempting to execute non-function ce." while testing. Please resolve the issue.
![Screenshot 2021-03-25 12 13 00 PM](https://user-images.githubusercontent.com/53495700/112530410-a38ae680-8d63-11eb-8efe-4bb5794db650.png)

**Comment by AGuski** [comment]
Thank you for opening this issue.
It is solved by a conditional check for the possibly missing function and improves the log messages when the check is negative. 
#6c62e82857de9603325c3f874aa872d279ec9dab
